import type { SecurityScene } from "@/schema/security-scene";

export function createBlankSecurityScene(): SecurityScene {
  const now = Date.now();

  return {
    id: `scene_${now.toString(36)}`,
    name: "Untitled Scene",
    createdAt: now,
    updatedAt: now,
    units: "meters",
    dimensions: { width: 10, depth: 8, height: 3 },
    walls: [
      {
        id: "wall_s",
        nodeType: "wall",
        label: "South Wall",
        start: [0, 0],
        end: [10, 0],
        heightM: 3,
        thicknessM: 0.18,
        material: "solid",
        visionTransmission: 0,
        source: "manual",
        reviewStatus: "unreviewed",
        sourceTrace: "",
        geometryValidity: "valid",
      },
      {
        id: "wall_n",
        nodeType: "wall",
        label: "North Wall",
        start: [0, 8],
        end: [10, 8],
        heightM: 3,
        thicknessM: 0.18,
        material: "solid",
        visionTransmission: 0,
        source: "manual",
        reviewStatus: "unreviewed",
        sourceTrace: "",
        geometryValidity: "valid",
      },
      {
        id: "wall_e",
        nodeType: "wall",
        label: "East Wall",
        start: [10, 0],
        end: [10, 8],
        heightM: 3,
        thicknessM: 0.18,
        material: "solid",
        visionTransmission: 0,
        source: "manual",
        reviewStatus: "unreviewed",
        sourceTrace: "",
        geometryValidity: "valid",
      },
      {
        id: "wall_w",
        nodeType: "wall",
        label: "West Wall",
        start: [0, 0],
        end: [0, 8],
        heightM: 3,
        thicknessM: 0.18,
        material: "solid",
        visionTransmission: 0,
        source: "manual",
        reviewStatus: "unreviewed",
        sourceTrace: "",
        geometryValidity: "valid",
      },
    ],
    doors: [],
    windows: [],
    cameras: [],
    securityLights: [],
    obstructions: [],
    criticalZones: [],
    privacyZones: [],
    sensors: [],
    entryPoints: [],
    paths: [],
    comments: [],
    assumptions: {
      wallHeightM: 3,
      personHeightM: 1.75,
      vehicleHeightM: 1.5,
      timeOfDay: "day",
      interiorLightLevel: "normal",
      nightPenaltyMode: "simple",
      doriStandard: "oodpcvs_2025",
      pixelsPerMeter: { detection: 25, observation: 62.5, recognition: 125, identification: 250 },
      showAssumptionsPanel: false,
      backlightIntensity: "none" as const,
      glareIntensity: "none" as const,
      overexposedZones: false,
    },
    source: "manual",
    reviewStatus: "unreviewed",
    sourceTrace: "",
    geometryValidity: "valid",
    version: "0.1.0",
    snapshots: [],
    scenarios: [],
    changeLog: [],
  };
}
