import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { formatTargetTypeLabel } from "@/components/view/camera-view-utils";

const cameraViewModePath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/CameraViewMode.tsx");
const cameraVerificationPanelPath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/camera-verification-panel.tsx");
const cameraVerificationUtilsPath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/camera-verification-utils.ts");

describe("CameraViewMode", () => {
  test("exposes the live overlay strip and replay presets", () => {
    const source = readFileSync(cameraViewModePath, "utf8");
    const panelSource = readFileSync(cameraVerificationPanelPath, "utf8");
    const utilsSource = readFileSync(cameraVerificationUtilsPath, "utf8");
    const combinedSource = `${source}\n${panelSource}\n${utilsSource}`;

    expect(source).toContain("VerificationPanel as SharedVerificationPanel");
    expect(panelSource).toContain("Footage Verification");

    expect(combinedSource).toContain("LIVE MODE (SIMULATED)");
    expect(combinedSource).toContain("DORI RANGES AT TARGET");
    expect(combinedSource).toContain("DORI OVERLAY");
    expect(combinedSource).toContain("REQUIRED ·");
    expect(combinedSource).toContain("PASSES");
    expect(combinedSource).toContain("FAILS");
    expect(combinedSource).toContain("Actor:");
    expect(combinedSource).toContain("Back to Map View");
    expect(combinedSource).toContain("Show replay essentials");
    expect(combinedSource).toContain("Minimal camera feed");
    expect(combinedSource).toContain("Inspection preset");
    expect(combinedSource).toContain("MORE");
    expect(combinedSource).toContain("Why this quality:");
    expect(combinedSource).toContain("Quality:");
    expect(combinedSource).toContain("Segment:");
    expect(combinedSource).toContain("Complete:");
    expect(combinedSource).toContain("Best Camera");
    expect(combinedSource).toContain("Operational Fusion");
    expect(combinedSource).toContain("Metadata:");
    expect(combinedSource).toContain("Connection:");
    expect(combinedSource).toContain("Sensors:");
    expect(combinedSource).toContain("Nearest:");
    expect(combinedSource).toContain("operationalFusion");
    expect(combinedSource).toContain("Live Sensor Event");
    expect(combinedSource).toContain("sensorEvent={latestSensorEvent}");
    expect(combinedSource).toContain("Live Camera Metadata");
    expect(combinedSource).toContain("cameraMetadataEvent={latestCameraMetadataEvent}");
    expect(combinedSource).toContain("Live Camera Connection");
    expect(combinedSource).toContain("cameraLiveConnectionEvent={latestCameraLiveConnectionEvent}");
    expect(combinedSource).toContain("Session:");
    expect(combinedSource).toContain("Session ID:");
    expect(combinedSource).toContain("Started:");
    expect(combinedSource).toContain("Confirmed:");
    expect(combinedSource).toContain("Expires:");
    expect(combinedSource).toContain("Transport:");
    expect(combinedSource).toContain("Protocol:");
    expect(combinedSource).toContain("Heartbeat:");
    expect(combinedSource).toContain("Footage Verification");
    expect(combinedSource).toContain("Planning aid only.");
    expect(combinedSource).toContain("Auto align");
    expect(combinedSource).toContain("autoAlignVerification");
    expect(combinedSource).toContain("evaluateAlignmentSample");
    expect(combinedSource).toContain("Reset align");
    expect(combinedSource).toContain("Overlay");
    expect(combinedSource).toContain("Split");
    expect(combinedSource).toContain("Alignment Quality");
    expect(combinedSource).toContain("Alignment Assist");
    expect(combinedSource).toContain("Auto align applied");
    expect(combinedSource).toContain("Manual offset controls are active for the current reference frame.");
    expect(combinedSource).toContain("Run auto align or use manual offsets after loading a reference frame.");
    expect(combinedSource).toContain("Difference heat overlay");
    expect(combinedSource).toContain("non-forensic");
    expect(combinedSource).toContain("accept=\"image/*,video/*\"");
    expect(combinedSource).toContain("Extracting video frame…");
    expect(combinedSource).toContain("Video frame sampled at");
    expect(combinedSource).toContain("extractVideoFrameDataUrl");
    expect(combinedSource).toContain("Extract frame at selected time");
    expect(combinedSource).toContain("Sample time");
    expect(combinedSource).toContain("verificationVideoFile");
    expect(combinedSource).toContain("extractFromCurrentVideo");
    expect(combinedSource).toContain("extractVideoFrameCandidates");
    expect(combinedSource).toContain("estimateFrameQuality");
    expect(combinedSource).toContain("Auto-pick best extracted frame");
    expect(combinedSource).toContain("Extracted frames");
    expect(combinedSource).toContain("verificationVideoCandidates");
    expect(combinedSource).toContain("verificationBestCandidateId");
    expect(combinedSource).toContain("sourceType: verificationSourceType");
    expect(combinedSource).toContain("sampleTimeS: verificationSampleTimeS");
    expect(combinedSource).toContain("videoDurationS: verificationVideoDurationS");
    expect(combinedSource).toContain("bestCandidateId: verificationBestCandidateId");
    expect(combinedSource).toContain("selectedCandidateId: verificationSelectedCandidateId");
    expect(combinedSource).toContain("alignmentMethod: verificationAlignmentMethod");
    expect(combinedSource).toContain("autoAlignDelta: verificationAutoAlignDelta");
    expect(combinedSource).toContain("scale: verificationScale");
    expect(combinedSource).toContain("setVerificationScale(snapshot.scale ?? 1)");
    expect(combinedSource).toContain("Reference scale");
    expect(combinedSource).toContain("Math.round(scale * 100)");
    expect(combinedSource).toContain("setVerificationAlignmentMethod(snapshot.alignmentMethod ?? null)");
    expect(combinedSource).toContain("setVerificationAutoAlignDelta(snapshot.autoAlignDelta ?? null)");
    expect(combinedSource).toContain("canAutoAlign={Boolean(verificationEnabled && verificationImageUrl && !verificationExtracting)}");
    expect(combinedSource).toContain("formatSnapshotEvidenceSummary");
    expect(combinedSource).toContain("Image upload");
    expect(combinedSource).toContain("manual align");
    expect(combinedSource).toContain("auto align");
    expect(combinedSource).toContain("frame set unavailable");
    expect(combinedSource).toContain("best frame selected");
    expect(combinedSource).toContain("manual frame selected");
    expect(combinedSource).toContain("no frame selected");
    expect(combinedSource).toContain("title={formatSnapshotEvidenceSummary(snapshot)}");
    expect(combinedSource).toContain("Excellent");
    expect(combinedSource).toContain("Good");
    expect(combinedSource).toContain("Fair");
    expect(combinedSource).toContain("Poor");
  });

  test("derives target labels from the zone target type", () => {
    expect(formatTargetTypeLabel("face_recognition")).toBe("Face");
    expect(formatTargetTypeLabel("cash_counter_activity")).toBe("Cash Counter");
    expect(formatTargetTypeLabel("door_entry_exit")).toBe("Entry / Exit");
  });
});
