import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { formatTargetTypeLabel } from "@/components/view/camera-view-utils";

const cameraViewModePath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/CameraViewMode.tsx");
const cameraVerificationWorkflowPath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/camera-verification-workflow.ts");
const cameraLiveFeedHudPath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/camera-live-feed-hud.tsx");
const cameraVerificationPanelPath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/camera-verification-panel.tsx");
const cameraVerificationUtilsPath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/camera-verification-utils.ts");
const cameraViewChromePath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../view/camera-view-chrome.tsx");

describe("CameraViewMode", () => {
  test("exposes the live overlay strip and replay presets", () => {
    const source = readFileSync(cameraViewModePath, "utf8");
    const workflowSource = readFileSync(cameraVerificationWorkflowPath, "utf8");
    const hudSource = readFileSync(cameraLiveFeedHudPath, "utf8");
    const panelSource = readFileSync(cameraVerificationPanelPath, "utf8");
    const utilsSource = readFileSync(cameraVerificationUtilsPath, "utf8");
    const chromeSource = readFileSync(cameraViewChromePath, "utf8");
    const combinedSource = `${source}\n${workflowSource}\n${hudSource}\n${panelSource}\n${utilsSource}\n${chromeSource}`;

    expect(source).toContain("VerificationPanel as SharedVerificationPanel");
    expect(source).toContain("Camera Focus Mode");
    expect(panelSource).toContain("Footage Verification");

    expect(combinedSource).toContain("Back to Map View");
    expect(combinedSource).toContain("Footage Verification");
    expect(combinedSource).toContain("Planning aid only.");
    expect(combinedSource).toContain("Auto align");
    expect(combinedSource).toContain("evaluateAlignmentSample");
    expect(combinedSource).toContain("Reset align");
    expect(combinedSource).toContain("Overlay");
    expect(combinedSource).toContain("Split");
    expect(combinedSource).toContain("Alignment Quality");
    expect(combinedSource).toContain("Alignment Assist");
    expect(combinedSource).toContain("Auto align applied");
    expect(combinedSource).toContain("Manual offset controls are active for the current reference frame.");
    expect(combinedSource).toContain("Run auto align or use manual offsets after loading a reference frame.");
    expect(combinedSource).toContain("Difference heat overlay");
    expect(combinedSource).toContain("Timeline / Path Replay");
    expect(combinedSource).toContain("Quality Over Time");
    expect(combinedSource).toContain("Camera Wall Preview");
    expect(combinedSource).toContain("activeCameraTimelineEvent");
    expect(combinedSource).toContain("flags.overlays && flags.path");
    expect(combinedSource).toContain("flags.overlays && flags.dori");
    expect(combinedSource).toContain("Replay Time");
    expect(combinedSource).toContain("Scenario / Path");
    expect(combinedSource).toContain("non-forensic");
    expect(combinedSource).toContain("Extracting video frame…");
    expect(combinedSource).toContain("Video frame sampled at");
    expect(combinedSource).toContain("extractVideoFrameDataUrl");
    expect(combinedSource).toContain("Extract frame at selected time");
    expect(combinedSource).toContain("Sample time");
    expect(combinedSource).toContain("verificationVideoFile");
    expect(combinedSource).toContain("extractFromCurrentVideo");
    expect(combinedSource).toContain("extractVideoFrameCandidates");
    expect(combinedSource).toContain("estimateFrameQuality");
    expect(combinedSource).toContain("Auto-pick best extracted frame");
    expect(combinedSource).toContain("Extracted frames");
    expect(combinedSource).toContain("verificationVideoCandidates");
    expect(combinedSource).toContain("verificationBestCandidateId");
    expect(combinedSource).toContain("bestCandidateScore");
    expect(combinedSource).toContain("Best frame");
    expect(combinedSource).toContain("score");
    expect(combinedSource).toContain("Frames are scored deterministically by sharpness.");
    expect(combinedSource).toContain("sourceType: verificationSourceType");
    expect(combinedSource).toContain("sampleTimeS: verificationSampleTimeS");
    expect(combinedSource).toContain("videoDurationS: verificationVideoDurationS");
    expect(combinedSource).toContain("bestCandidateId: verificationBestCandidateId");
    expect(combinedSource).toContain("selectedCandidateId: verificationSelectedCandidateId");
    expect(combinedSource).toContain("recordOperationalEvidenceEvent");
    expect(combinedSource).toContain("snapshot_saved");
    expect(combinedSource).toContain("Camera verification snapshot saved");
    expect(combinedSource).toContain("branchLabel: \"verification\"");
    expect(combinedSource).toContain("alignmentMethod: verificationAlignmentMethod");
    expect(combinedSource).toContain("autoAlignDelta: verificationAutoAlignDelta");
    expect(combinedSource).toContain("scale: verificationScale");
    expect(combinedSource).toContain("setVerificationScale(snapshot.scale ?? 1)");
    expect(combinedSource).toContain("Reference scale");
    expect(combinedSource).toContain("Math.round(scale * 100)");
    expect(combinedSource).toContain("setVerificationAlignmentMethod(snapshot.alignmentMethod ?? null)");
    expect(combinedSource).toContain("setVerificationAutoAlignDelta(snapshot.autoAlignDelta ?? null)");
    expect(combinedSource).toContain("canAutoAlign={verification.canAutoAlign}");
    expect(combinedSource).toContain("formatSnapshotEvidenceSummary");
    expect(combinedSource).toContain("Image upload");
    expect(combinedSource).toContain("manual align");
    expect(combinedSource).toContain("auto align");
    expect(combinedSource).toContain("frame set unavailable");
    expect(combinedSource).toContain("best frame selected");
    expect(combinedSource).toContain("manual frame selected");
    expect(combinedSource).toContain("no frame selected");
    expect(combinedSource).toContain("best score");
    expect(combinedSource).toContain("title={formatSnapshotEvidenceSummary(snapshot)}");
    expect(combinedSource).toContain("Excellent");
    expect(combinedSource).toContain("Good");
    expect(combinedSource).toContain("Fair");
    expect(combinedSource).toContain("Poor");
    expect(combinedSource).toContain("Auth:");
    expect(combinedSource).toContain("Auth session:");
    expect(combinedSource).toContain("Challenge:");
    expect(source).toContain('from "@/components/view/camera-view-utils"');
    expect(source).toContain("buildReplayStateByCameraAtTime,");
    expect(source).toContain("clampPathDuration,");
    expect(source).toContain("clampReplayProgress,");
    expect(source).toContain("orderCamerasForReplayPlayback,");
    expect(source).toContain("const safeReplayDurationS = replayClock.durationS;");
    expect(source).toContain("const pathTimeS = replayClock.timeS;");
    expect(source).toContain("totalSeconds={safeReplayDurationS}");
    expect(source).not.toContain("function clampReplayProgress(progress");
    expect(source).not.toContain("function clampPathDuration(durationS");
    expect(source).not.toContain("return orderCamerasForReplayPlayback");
    expect(source).not.toContain("const safeReplayDurationS = activePathResult?.totalDurationS > 0");
    expect(source).toContain("st-camera-view-safe-zone");
    expect(source).toContain("--st-full-canvas-safe-top");
    expect(source).toContain("const \[immersiveMode, setImmersiveMode\] = useState(false);");
    expect(source).toContain("toggleActiveSurfaceFocus");
    expect(source).toContain("Press F to exit focus");
    expect(source).toContain("const toggleImmersiveMode = useCallback(() => {");
    expect(source).toContain("window.addEventListener(STUDIO_SHORTCUT_EVENTS.toggleActiveSurfaceFocus, toggleImmersiveMode);");
    expect(chromeSource).toContain("Exit Focus");
    expect(chromeSource).toContain("Feed mode:");
  });

  test("derives target labels from the zone target type", () => {
    expect(formatTargetTypeLabel("face_recognition")).toBe("Face");
    expect(formatTargetTypeLabel("cash_counter_activity")).toBe("Cash Counter");
    expect(formatTargetTypeLabel("door_entry_exit")).toBe("Entry / Exit");
  });
});
