import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const dashboardHomePath = resolve(fileURLToPath(new URL(".", import.meta.url)), "../launcher/StudioDashboardHome.tsx");

describe("Studio dashboard launcher surface", () => {
  test("surfaces the launcher entry flows and project/status cards", () => {
    const source = readFileSync(dashboardHomePath, "utf8");

    expect(source).toContain("Security Simulation Workspace");
    expect(source).toContain("Open Studio");
    expect(source).toContain("Run Simulation");
    expect(source).toContain("Import JSON");
    expect(source).toContain("New Scene");
    expect(source).toContain("Last run: Never");
    expect(source).toContain("Day Mode");
    expect(source).toContain("Workspace Modes");
    expect(source).toContain("Map & Analysis");
    expect(source).toContain("Single Camera");
    expect(source).toContain("Route Analysis");
    expect(source).toContain('viewMode: "map" as const');
    expect(source).toContain("Scan a Site");
    expect(source).toContain("status=\"Preview / Manual-assisted\"");
    expect(source).toContain("Build a security scene from site photos by marking walls, doors, cameras, obstructions, lights, and critical zones.");
    expect(source).toContain("Start Scan");
    expect(source).toContain("manual-assisted");
    expect(source).toContain("Current Workspace Preview");
    expect(source).toContain("Coverage (PPM)");
    expect(source).toContain("250+ Identification");
    expect(source).toContain("2D");
    expect(source).toContain("3D");
    expect(source).toContain("Recent Workspaces");
    expect(source).toContain("Search, pin, and reopen your workspaces first. The demo remains available as the reference baseline below.");
    expect(source).toContain("Quick Start");
    expect(source).toContain("Entry flow maturity");
    expect(source).toContain("Manual-assisted now");
    expect(source).toContain("Scan Site (manual-assisted)");
    expect(source).toContain("Guided scan reconstruction");
    expect(source).toContain("Open Workspace");
    expect(source).toContain("Open Coverage Workspace");
    expect(source).toContain("Open Coverage");
    expect(source).toContain("Your Workspaces");
    expect(source).toContain("Blank Workspace");
    expect(source).toContain("Import Workspace");
    expect(source).toContain("Scan Workspace");
    expect(source).toContain("AI Draft Workspace");
    expect(source).toContain("badge=\"Blank\"");
    expect(source).toContain("badge=\"Import\"");
    expect(source).toContain("badge=\"Scan\"");
    expect(source).toContain("badge=\"AI\"");
    expect(source).toContain("tone=\"blank\"");
    expect(source).toContain("tone=\"import\"");
    expect(source).toContain("tone=\"scan\"");
    expect(source).toContain("tone=\"ai\"");
    expect(source).toContain("WorkspaceMiniPreview");
    expect(source).toContain("Loading preview");
    expect(source).toContain("Preview loading");
    expect(source).toContain("const hydrated = useSyncExternalStore(");
    expect(source).toContain('const manualScanFeature = featureStatus.find((entry) => entry.feature === "Scan Site (manual-assisted)") ?? null;');
    expect(source).toContain('const guidedScanFeature = featureStatus.find((entry) => entry.feature === "Guided scan reconstruction") ?? null;');
    expect(source).toContain('const aiLayoutDraftFeature = featureStatus.find((entry) => entry.feature === "AI layout draft") ?? null;');
    expect(source).toContain('const verifyFootageFeature = featureStatus.find((entry) => entry.feature === "Real footage verification") ?? null;');
    expect(source).toContain("Reference Demo");
    expect(source).toContain("Draft Workspace");
    expect(source).toContain("Draft");
    expect(source).toContain("sourceBadgeTone");
    expect(source).toContain("Project metadata");
    expect(source).toContain("All tags");
    expect(source).toContain("All sources");
    expect(source).toContain('const [activeSource, setActiveSource] = useState<ProjectSourceFilter>("All");');
    expect(source).toContain("Pin");
    expect(source).toContain("Duplicate Workspace");
    expect(source).toContain("Rename Workspace");
    expect(source).toContain("onDuplicateProject={onDuplicateProject}");
    expect(source).toContain("onRenameProject={onRenameProject}");
    expect(source).toContain("Project metadata");
    expect(source).toContain("Security Status");
    expect(source).toContain("OUTCOME SUMMARY");
    expect(source).toContain("OPEN ISSUES");
    expect(source).toContain("SIMULATION ASSUMPTIONS");
    expect(source).toContain("See all issues & recommendations");
    expect(source).toContain("Open Report");
    expect(source).toContain("Edit in Studio");
    expect(source).toContain("AI Layout Draft");
    expect(source).toContain("Product feature status");
    expect(source).toContain("All systems operational");
    expect(source).toContain("Security Simulation Studio");
  });
});
