import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";

const reportLitePath = new URL("../bottom-panel/ReportLiteTab.tsx", import.meta.url);

describe("ReportLiteTab", () => {
  test("exposes markdown and html export actions for the handoff report", () => {
    const source = readFileSync(reportLitePath, "utf8");

    expect(source).toContain("Export Markdown");
    expect(source).toContain("handleExportMarkdown");
    expect(source).toContain("exportCompareAsMarkdown");
    expect(source).toContain("Export HTML");
    expect(source).toContain("Export Evidence Bundle");
    expect(source).toContain("Export PDF");
    expect(source).toContain("handleExportPdf");
    expect(source).toContain("exportTextAsPdf");
    expect(source).toContain("compareReportSelection ? \"compare\" : \"single\"");
    expect(source).toContain("Copy");
    expect(source).toContain("Share compare link");
    expect(source).toContain("Copy compare link");
    expect(source).toContain("Compare provenance:");
    expect(source).toContain("Print");
    expect(source).toContain("Report Summary");
    expect(source).toContain("TruthBadge");
    expect(source).toContain('label="computed"');
    expect(source).toContain("buildReportSummaryLines");
    expect(source).toContain("getReportStandardTemplates");
    expect(source).toContain("Save preset");
    expect(source).toContain("Catalog");
    expect(source).toContain("Standards template");
    expect(source).toContain("Template");
    expect(source).toContain("Preset name");
    expect(source).toContain("Saved presets");
    expect(source).toContain("Remove");
    expect(source).toContain("Audience");
    expect(source).toContain("reportAudience");
    expect(source).toContain("Visibility");
    expect(source).toContain("reportVisibility");
    expect(source).toContain("reportTemplateId");
    expect(source).toContain("Audience Policy");
    expect(source).toContain("disclosureSummary");
    expect(source).toContain("Visible Sections");
    expect(source).toContain("Withheld Sections");
    expect(source).toContain("Latest Run");
    expect(source).toContain("Truth Ladder");
    expect(source).toContain("Best Zone Quality");
    expect(source).toContain("Zones Failed");
    expect(source).toContain("Temporal Operational Twin");
    expect(source).toContain("Reconstructable Checkpoints");
    expect(source).toContain("Published Checkpoints");
    expect(source).toContain("Checkpoint Age");
    expect(source).toContain("Latest Published Checkpoint");
    expect(source).toContain("Published Age");
    expect(source).toContain("summarizeSceneTruthLadder");
    expect(source).toContain("Occlusion Blame");
    expect(source).toContain("Quality Without");
    expect(source).toContain("Operational evidence");
  });
});
