"use client";

import { useCallback, useMemo, useState } from "react";
import { useStudioStore } from "@/store/studio-store";
import { RunSimulationPrompt } from "@/components/shared/RunSimulationPrompt";
import { TruthBadge } from "@/components/shared/TruthBadge";
import { writeClipboardText } from "@/lib/share-link";
import {
  computeBudget,
  CABLE_COST_PER_METER,
  LABOR_RATE_PER_HOUR,
  type CoverageBudget,
} from "@/lib/coverage-budgeting";
import { UI_SURFACES } from "@/lib/studio-surface-tokens";

// ── Format helpers ────────────────────────────────────────────────────────────

const fmt = (n: number) =>
  n.toLocaleString("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 0, maximumFractionDigits: 0 });

const fmtHours = (h: number) => `${h.toFixed(1)} hrs`;

function confidenceColor(confidence: "estimate" | "precise") {
  return confidence === "precise"
    ? { ring: "#22c55e", text: "#4ade80" }
    : { ring: "#eab308", text: "#facc15" };
}

// ── Main component ─────────────────────────────────────────────────────────────

export function CoverageBudgetTab() {
  const scene = useStudioStore((s) => s.scene);
  const result = useStudioStore((s) => s.simulationResult);

  const [budget, setBudget] = useState<CoverageBudget | null>(null);

  const hasSceneData = scene.cameras.length > 0 || scene.securityLights.length > 0;

  const runBudget = useCallback(() => {
    const b = computeBudget(scene);
    setBudget(b);
  }, [scene]);

  // Color ring for the confidence badge
  const confCol = budget ? confidenceColor(budget.confidence) : { ring: "#3a4158", text: "#68738a" };

  // ── Export handler ───────────────────────────────────────────────────────
  const exportSummary = useCallback(() => {
    if (!budget) return;
    const lines = [
      "═══════════════════════════════════════════",
      "  Coverage Budget Summary",
      "═══════════════════════════════════════════",
      "",
      `  Total Cost:       ${fmt(budget.totalCost)}`,
      `  Hardware:         ${fmt(budget.hardwareCost)}`,
      `  Installation:     ${fmt(budget.installationCost)}`,
      `  Cabling:          ${fmt(budget.cablingCost)}`,
      `  Estimated Hours:  ${fmtHours(budget.estimatedHours)}`,
      `  Confidence:       ${budget.confidence === "precise" ? "Precise" : "Estimate"}`,
      "",
      "── Cameras ──",
      ...budget.breakdownByCamera.map(
        (c) =>
          `  ${c.name.padEnd(20)} ${fmt(c.cost).padStart(8)}  install ${fmt(c.installation).padStart(7)}  total ${fmt(c.total).padStart(8)}`,
      ),
      "",
      ...(budget.breakdownByLight.length > 0
        ? [
            "── Lights ──",
            ...budget.breakdownByLight.map(
              (l) =>
                `  ${l.name.padEnd(20)} ${fmt(l.cost).padStart(8)}  install ${fmt(l.installation).padStart(7)}  total ${fmt(l.total).padStart(8)}`,
            ),
            "",
          ]
        : []),
      ...(budget.optionalCosts.length > 0
        ? [
            "── Optional ──",
            ...budget.optionalCosts.map(
              (o) => `  ${o.label.padEnd(20)} ${fmt(o.cost).padStart(8)}`,
            ),
            "",
          ]
        : []),
      "═══════════════════════════════════════════",
      "  Generated by SentinelTwin Coverage Budget",
    ].join("\n");

    void writeClipboardText(lines);
  }, [budget]);

  const isEmpty = !budget;

  return (
    <div className="flex h-full flex-col overflow-hidden">

      {/* ── Stats strip ───────────────────────────────────────────────── */}
      {budget && (
        <div className={`{flex flex-shrink-0 items-center gap-3 border-b UI_SURFACES.borderPanel UI_SURFACES.panelDeepAlt px-3 py-1}`}>

          <TruthBadge label="simulated" />

          {/* Confidence badge */}
          <div className="flex items-center gap-2">
            <div
              className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full border-2"
              style={{ borderColor: confCol.ring }}
            >
              <span className="font-mono text-[8px] font-bold" style={{ color: confCol.text }}>
                {budget.confidence === "precise" ? "PR" : "ES"}
              </span>
            </div>
            <div>
              <div className={`text-[10px] font-semibold UI_SURFACES.textBody leading-tight`}>{fmt(budget.totalCost)}</div>
              <div className={`text-[8px] UI_SURFACES.textMuted`}>Estimated Total</div>
            </div>
          </div>

          <div className={`h-5 w-px UI_SURFACES.bgPanel`} />

          {/* Stat chips */}
          {([
            { label: "Hardware", value: fmt(budget.hardwareCost), color: "text-blue-300" },
            { label: "Install",  value: fmt(budget.installationCost), color: "text-amber-300" },
            { label: "Cabling",  value: fmt(budget.cablingCost), color: "text-purple-300" },
            { label: "Hours",    value: fmtHours(budget.estimatedHours), color: `UI_SURFACES.textBody` },
          ] as const).map(({ label, value, color }) => (
            <div key={label} className="flex items-baseline gap-1">
              <span className={`font-mono text-[11px] font-bold ${color}`}>{value}</span>
              <span className={`text-[8px] uppercase tracking-wide UI_SURFACES.textDim`}>{label}</span>
            </div>
          ))}

          {/* Export button */}
          <button
            type="button"
            onClick={exportSummary}
            className={`ml-auto rounded border UI_SURFACES.borderStrong UI_SURFACES.card px-2 py-1 text-[9px] font-semibold UI_SURFACES.textNear transition-colors hover:border-sky-400/30 hover:text-white`}
          >
            Export Summary
          </button>
        </div>
      )}

      {/* ── Content area ───────────────────────────────────────────────── */}
      <div className="flex flex-1 min-h-0 overflow-hidden">
        {isEmpty ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-3 px-4">
            {!hasSceneData ? (
              <div className="text-center">
                <div className={`text-[11px] UI_SURFACES.textDim`}>
                  Add cameras or lights to the scene, then run the budget.
                </div>
              </div>
            ) : !result ? (
              <RunSimulationPrompt
                className="px-4"
                message="Run the simulation first, then compute the coverage budget for the current scene."
              />
            ) : (
              <div className="text-center">
                <div className={`mb-2 text-[10px] UI_SURFACES.textDim`}>
                  Scene has {scene.cameras.length} camera{scene.cameras.length === 1 ? "" : "s"}
                  {scene.securityLights.length > 0
                    ? ` and ${scene.securityLights.length} light${scene.securityLights.length === 1 ? "" : "s"}`
                    : ""}
                  .
                </div>
                <button
                  type="button"
                  onClick={runBudget}
                  className="rounded-lg border border-green-500/30 bg-green-500/10 px-4 py-2 text-[11px] font-semibold text-green-300 transition-colors hover:bg-green-500/20 hover:text-green-200"
                >
                  Run Budget
                </button>
              </div>
            )}
          </div>
        ) : (
          <div className="flex flex-1 overflow-auto">
            <div className="flex-1 p-2">
              {/* ── Camera breakdown table ───────────────────────────────── */}
              {budget.breakdownByCamera.length > 0 && (
                <div className="mb-3">
                  <div className={`mb-1 text-[9px] font-semibold uppercase tracking-wider UI_SURFACES.textMuted5`}>
                    Camera Costs
                  </div>
                  <table className="w-full border-collapse text-[9px]">
                    <thead>
                      <tr className={`{border-b UI_SURFACES.borderPanel}`}>
                        <th className={`px-2 py-1 text-left text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Camera</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Hardware</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Install</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Cabling</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Total</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Hours</th>
                      </tr>
                    </thead>
                    <tbody>
                      {budget.breakdownByCamera.map((c) => (
                        <tr key={c.cameraId} className={`border-b UI_SURFACES.borderFaint transition-colors UI_SURFACES.hoverBgSubtle`}>
                          <td className={`px-2 py-1 text-left UI_SURFACES.textBody`}>{c.name}</td>
                          <td className={`px-2 py-1 text-right font-mono UI_SURFACES.textMuted5`}>{fmt(c.cost)}</td>
                          <td className={`px-2 py-1 text-right font-mono UI_SURFACES.textMuted5`}>{fmt(c.installation)}</td>
                          <td className={`px-2 py-1 text-right font-mono UI_SURFACES.textMuted5`}>{fmt(c.cabling)}</td>
                          <td className={`px-2 py-1 text-right font-mono font-semibold UI_SURFACES.textBody`}>{fmt(c.total)}</td>
                          <td className={`px-2 py-1 text-right font-mono UI_SURFACES.textSoftMid`}>{c.laborHours.toFixed(1)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {/* ── Light breakdown table ────────────────────────────────── */}
              {budget.breakdownByLight.length > 0 && (
                <div className="mb-3">
                  <div className={`mb-1 text-[9px] font-semibold uppercase tracking-wider UI_SURFACES.textMuted5`}>
                    Light Costs
                  </div>
                  <table className="w-full border-collapse text-[9px]">
                    <thead>
                      <tr className={`{border-b UI_SURFACES.borderPanel}`}>
                        <th className={`px-2 py-1 text-left text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Light</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Hardware</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Install</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Total</th>
                        <th className={`px-2 py-1 text-right text-[8px] font-medium uppercase tracking-wider UI_SURFACES.textDim`}>Hours</th>
                      </tr>
                    </thead>
                    <tbody>
                      {budget.breakdownByLight.map((l) => (
                        <tr key={l.lightId} className={`border-b UI_SURFACES.borderFaint transition-colors UI_SURFACES.hoverBgSubtle`}>
                          <td className={`px-2 py-1 text-left UI_SURFACES.textBody`}>{l.name}</td>
                          <td className={`px-2 py-1 text-right font-mono UI_SURFACES.textMuted5`}>{fmt(l.cost)}</td>
                          <td className={`px-2 py-1 text-right font-mono UI_SURFACES.textMuted5`}>{fmt(l.installation)}</td>
                          <td className={`px-2 py-1 text-right font-mono font-semibold UI_SURFACES.textBody`}>{fmt(l.total)}</td>
                          <td className={`px-2 py-1 text-right font-mono UI_SURFACES.textSoftMid`}>{l.laborHours.toFixed(1)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {/* ── Optional costs ────────────────────────────────────────── */}
              {budget.optionalCosts.length > 0 && (
                <div className="mb-3">
                  <div className={`mb-1 text-[9px] font-semibold uppercase tracking-wider UI_SURFACES.textMuted5`}>
                    Optional Costs
                  </div>
                  <div className="space-y-1">
                    {budget.optionalCosts.map((o, i) => (
                      <div
                        key={i}
                        className="flex items-center justify-between rounded-lg border border-amber-700/30 bg-amber-900/8 px-2.5 py-1.5"
                      >
                        <div className="flex flex-col">
                          <span className="text-[9px] font-medium text-amber-200">{o.label}</span>
                          <span className={`text-[8px] UI_SURFACES.textMuted`}>{o.description}</span>
                        </div>
                        <span className="flex-shrink-0 font-mono text-[10px] font-semibold text-amber-300">
                          {fmt(o.cost)}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* ── Re-run button at bottom ───────────────────────────────── */}
              <div className="flex items-center gap-2 pb-2">
                <button
                  type="button"
                  onClick={runBudget}
                  className={`rounded border UI_SURFACES.borderStrong UI_SURFACES.card px-2.5 py-1 text-[9px] font-semibold UI_SURFACES.textNear transition-colors hover:border-green-400/30 hover:text-white`}
                >
                  Re-run Budget
                </button>
                <button
                  type="button"
                  onClick={exportSummary}
                  className={`rounded border UI_SURFACES.borderStrong UI_SURFACES.card px-2.5 py-1 text-[9px] font-semibold UI_SURFACES.textNear transition-colors hover:border-sky-400/30 hover:text-white`}
                >
                  Copy Summary
                </button>
              </div>
            </div>

            {/* ── Sidebar: constants reference ────────────────────────────── */}
            <div className={`{w-[144px] flex-shrink-0 border-l UI_SURFACES.borderPanel p-2}`}>
              <div className={`mb-1 text-[7px] font-semibold uppercase tracking-wider UI_SURFACES.textDim`}>
                Rates
              </div>
              <div className="space-y-0.5">
                <div className="flex justify-between text-[8px]">
                  <span className={`UI_SURFACES.textMuted`}>Cable / m</span>
                  <span className={`font-mono UI_SURFACES.textSoftMid`}>{fmt(CABLE_COST_PER_METER)}</span>
                </div>
                <div className="flex justify-between text-[8px]">
                  <span className={`UI_SURFACES.textMuted`}>Labor / hr</span>
                  <span className={`font-mono UI_SURFACES.textSoftMid`}>{fmt(LABOR_RATE_PER_HOUR)}</span>
                </div>
              </div>

              <div className={`mb-1 mt-2 text-[7px] font-semibold uppercase tracking-wider UI_SURFACES.textDim`}>
                Mount
              </div>
              <div className="space-y-0.5">
                {(["wall", "ceiling", "pole", "corner", "desk"] as const).map((type) => {
                  const rate = type === "wall" ? 75
                    : type === "ceiling" ? 95
                    : type === "pole" ? 120
                    : type === "corner" ? 110
                    : 45;
                  return (
                    <div key={type} className="flex justify-between text-[8px]">
                      <span className={`UI_SURFACES.textMuted capitalize`}>{type}</span>
                      <span className={`font-mono UI_SURFACES.textSoftMid`}>{fmt(rate)}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
